### ISSUE TITLE
建议更新文档中有关selenium的教程

### ISSUE THREAD

**Issue by lyc280705** [west2-online-reserve/collection-python#55]
现有教程在v4.0不适用，以下是部分最新教程：<https://blog.csdn.net/stitchD/article/details/123818886> 、<https://www.selenium.dev/documentation/>

**Comment by WuJunkai2004** [comment]
可以拉个PR
docs(work2/readme.md) : 更新 selelnium 相关教程

**Comment by linrongda** [comment]
> 可以拉个PR docs(work2/readme.md) : 更新 selelnium 相关教程

√

**Comment by lyc280705** [comment]
已更改

**Comment by linrongda** [comment]
啊不对，learn那边也要改，我来更新吧

**Comment by linrongda** [comment]
文档要更新的地方挺多的，到时候会统一更新
感谢提议！
